source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'rest-client', '1.7.3'
gem 'json'
gem 'docker-api'
gem 'pony'
gem 'sshkey'
gem 'cocaine'
gem 'redis'
gem 'facter'
gem 'rack-flash3'
gem 'mongoid', '~> 5.0.0'
gem 'require_all'